@echo off
SETX DOT_CID_GITLAB_USER matt
SETX DOT_CID_GITLAB_TOKEN B7f8DnDsNpFeF95pXFF9
SETX DOT_CID_GITLAB_URL http://nas
SETX DOT_CID_JENKINS_TOKEN 112bd7be12a2ea1df43b2efb0bbd39b5d4
SETX DOT_CID_JENKINS_URL http://nas:8081
SETX DOT_CID_JENKINS_USER matt
rem SETX DOT_CID_NUGET_FEED \\nas\packages
