@rem THIS FILE WAS GENERATED BY .pack.cmd COMMAND 
@call _dots %~n0 "Install global dots or upgrade local dots" "[install^|upgrade]" "" %1 %2 %3 
if %ERRORLEVEL% equ 1 exit /b 
echo .dots 1.3.0-alpha.73 %DOT_TYPE% 
set PARAM=%1 
if /i "%PARAM:~0,2%" neq "up" goto install 
if "%DOT_TYPE%" neq "local" goto exit 
if exist .\.dots\ del /q .\.dots\*.* 
dotnet new dots --force 
call .dots 
goto exit 
:install 
if /i "%PARAM:~0,1%" neq "i" goto exit 
if "%DOT_TYPE%" neq "local" goto exit 
if exist %DOT_PATH_GLOBAL% del /q %DOT_PATH_GLOBAL%\*.* 
if not exist %DOT_PATH_GLOBAL% mkdir %DOT_PATH_GLOBAL% 2>nul 
copy %DOT_PATH%\*.cmd %DOT_PATH_GLOBAL% > nul 
echo .dots copied to %DOT_PATH_GLOBAL% 
if "%2" equ "noprereq" goto exit 
%DOT_PATH%_install.cmd 
:exit 
